project:
  type: website
  resources: .gitlab-ci.yml
  post-render: scripts/date.py
website:
  repo-url: https://github.com/maptv/maptv.github.io
  repo-actions: [source]
  back-to-top-navigation: true
  reader-mode: true
  page-navigation: true
  favicon: media/dec.png
  navbar:
    title: Martin Laptev
    logo: media/dec.png
    logo-alt: "10-point star made up of 100 triangles"
    right:
      - icon: person-circle
        file: about.qmd
        text: About
      - icon: pencil
        file: blog/blog.qmd
        text: Blog
      - icon: file-earmark-person
        file: cv/cv.qmd
        text: CV
      - icon: github
        href: https://github.com/maptv
      - icon: linkedin
        href: https://linkedin.com/in/maptv
      - icon: envelope
        href: mailto:maptv@vt.edu
  twitter-card: true
  site-url: https://maptv.github.io
  sidebar:
    collapse-level: 3
    search: true
    sort: order
    style: floating
    title: none
    contents:
      - text: About
        file: about.qmd
      - section: Blog
        file: blog/blog.qmd
        contents:
          - section: Tools
            href: blog/#category=tool
            contents:
              - blog/git/git.qmd
              - blog/vscode/vscode.qmd
              - blog/quarto/quarto.qmd
              - blog/observable/observable.qmd
              - blog/jupyter/jupyter.qmd
              - blog/knitr/knitr.qmd
          - section: Machine Learning
            href: blog/#category=ml
            contents:
              - blog/prob/prob.qmd
              - blog/llm/llm.qmd
      - text: Curriculum Vitae
        file: cv/cv.qmd
      - text: GitHub
        href: https://github.com/maptv
      - text: LinkedIn
        href: https://linkedin.com/in/maptv
      - text: Mail
        href: mailto:maptv@vt.edu
format:
  html:
    page-layout: full
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    css: styles.css
    grid:
      sidebar-width: 150px
      body-width: 1800px
      margin-width: 250px
execute:
  freeze: true
  cache: true
