project:
  type: website
  resources: .gitlab-ci.yml
  post-render: date.py
website:
  back-to-top-navigation: true
  reader-mode: true
  page-navigation: true
  favicon: media/dec.png
  navbar:
    title: Martin Laptev
    logo: media/dec.png
    logo-alt: "10-point star made up of 100 triangles"
    right:
      - icon: person-circle
        file: about.qmd
        text: About
      - icon: pencil
        file: blog/blog.qmd
        text: Blog
      - icon: file-earmark-person
        file: cv/cv.qmd
        text: CV
      - icon: github
        href: https://github.com/maptv
      - icon: linkedin
        href: https://linkedin.com/in/maptv
      - icon: envelope
        href: mailto:maptv@vt.edu
  twitter-card: true
  sidebar:
    search: true
    sort: order
    style: floating
    title: none
    contents:
      - text: About
        file: about.qmd
      - section: Blog
        file: blog/blog.qmd
        contents:
          - blog/quarto/quarto.qmd
          - blog/observable/observable.qmd
          - blog/jupyter/jupyter.qmd
          - blog/knitr/knitr.qmd
      - text: Curriculum Vitae
        file: cv/cv.qmd
      - text: GitHub
        href: https://github.com/maptv
      - text: LinkedIn
        href: https://linkedin.com/in/maptv
      - text: Mail
        href: mailto:maptv@vt.edu
format:
  html:
    page-layout: full
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    css: styles.css
    grid:
      sidebar-width: 200px
      body-width: 1800px
      margin-width: 200px
execute:
  freeze: true
  cache: true
