project:
  type: website
  resources: .gitlab-ci.yml
  post-render:
  - assets/date.py
website:
  search:
    location: sidebar
    type: overlay
    keyboard-shortcut: ["/", "?", "h", "f", "s"]
    copy-button: true
    show-item-context: true
  page-navigation: true
  site-url: https://maptv.github.io
  repo-url: https://github.com/maptv/maptv.github.io
  repo-actions: [source]
  back-to-top-navigation: true
  reader-mode: true
  draft-mode: visible
  favicon: assets/deidek.svg
  navbar:
    title: Martin Laptev
    logo: assets/deidek.svg
    logo-alt: "Decagon made up of 100 triangles"
  sidebar:
    tools:
    - icon: github
      href: https://www.github.com/maptv
      target: _blank
    - icon: linkedin
      href: https://www.linkedin.com/in/maptv
      target: _blank
    - icon: envelope-at
      href: mailto:maptv@engineer.com
    collapse-level: 3
    contents:
    - icon: house-door
      text: Home
      href: index.qmd
    - icon: info-circle
      text: About
      href: about/index.qmd
    - icon: file-earmark-person
      text: CV/Résumé
      href: cv/index.qmd
    - icon: pencil
      section: Blog
      href: blog/index.qmd
      contents:
      - section: Measurement
        icon: rulers
        href: blog/dec/index.qmd
        contents:
        - text: Geolocation
          icon: geo
          href: blog/geo/index.qmd
        - text: Decimal time
          icon: hourglass-split
          href: blog/time/index.qmd
        - text: Ordinal date
          icon: calendar-event
          href: blog/date/index.qmd
        - text: Daylight duration
          icon: sun
          href: blog/day/index.qmd
        - text: Time interval
          icon: calendar-range
          href: blog/interval/index.qmd
        - text: Navigation
          icon: compass
          href: blog/nav/index.qmd
        - text: Movement
          icon: arrows-move
          href: blog/move/index.qmd
        - text: Size
          icon: bounding-box-circles
          href: blog/size/index.qmd
      - section: Software Tools
        icon: tools
        contents:
        - icon: git
          text: Git
          href: blog/git/index.qmd
        - icon: code
          text: VSCode
          href: blog/vscode/index.qmd
        - icon: journal-richtext
          text: Jupyter
          href: blog/jupyter/index.qmd
        - icon: markdown
          text: Quarto Markdown
          href: blog/quarto/index.qmd
        - icon: 0-circle
          text: Observable
          href: blog/observable/index.qmd
      - section: Machine Learning
        icon: robot
        contents:
        - icon: dice-5
          text: Probablity
          href: blog/prob/index.qmd
        - icon: translate
          text: Language Models
          href: blog/llm/index.qmd
  twitter-card: true
  page-footer:
    background: light
    left: © Copyright 2024, Martin Laptev
    right:
    - icon: github
      href: https://github.com/maptv
      target: _blank
    - icon: linkedin
      href: https://linkedin.com/in/maptv
      target: _blank
    - icon: envelope-at
      href: mailto:maptv@engineer.com
format:
  html:
    pagetitle: Martin Laptev
    page-layout: full
    mainfont: Lato
    toc: true
    theme:
      light: [flatly, assets/light.scss]
      dark: [darkly, assets/dark.scss]
    grid:
      sidebar-width: 161px
      body-width: 1800px
      margin-width: 161px
    css: assets/styles.css
execute:
  freeze: true
  cache: true
