project:
  type: website
  resources: .gitlab-ci.yml
website:
  page-navigation: true
  site-url: https://maptv.github.io
  repo-url: https://github.com/maptv/maptv.github.io
  repo-actions: [source]
  back-to-top-navigation: true
  reader-mode: true
  favicon: media/deidek.svg
  navbar:
    title: Martin Laptev
    logo: media/deidek.svg
    logo-alt: "Decagon made up of 100 triangles"
    right:
      - icon: pencil
        menu:
          - icon: git
            text: Git
            href: blog/git/git.qmd
          - icon: code
            text: VSCode
            href: blog/vscode/vscode.qmd
          - icon: journal-richtext
            text: Jupyter
            href: blog/jupyter/jupyter.qmd
          - icon: markdown
            text: Quarto Markdown
            href: blog/quarto/quarto.qmd
          - icon: 0-circle
            text: Observable
            href: blog/observable/observable.qmd
          - icon: dice-5
            text: Probablity
            href: blog/prob/prob.qmd
          - icon: translate
            text: Language Models
            href: blog/llm/llm.qmd
  sidebar:
    tools:
      - icon: github
        href: https://www.github.com/maptv
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/maptv
        target: _blank
      - icon: envelope-at
        href: mailto:maptv@engineer.com
    collapse-level: 2
    contents:
      - icon: house-door
        text: Home
        href: index.qmd
      - icon: info-circle
        text: About
        href: about/index.qmd
      - icon: file-earmark-person
        text: Résumé
        href: cv/index.qmd
      - icon: pencil
        section: Blog
        href: blog/index.qmd
        contents:
          - text: "---"
          - section: Tools
            icon: tools
            href: blog/#category=tool
            contents:
              - icon: git
                text: Git
                href: blog/git/git.qmd
              - icon: code
                text: VSCode
                href: blog/vscode/vscode.qmd
              - icon: journal-richtext
                text: Jupyter
                href: blog/jupyter/jupyter.qmd
              - icon: markdown
                text: Quarto Markdown
                href: blog/quarto/quarto.qmd
              - icon: 0-circle
                text: Observable
                href: blog/observable/observable.qmd
          - text: "---"
          - section: Machine Learning
            icon: robot
            href: blog/#category=ml
            contents:
              - icon: dice-5
                text: Probablity
                href: blog/prob/prob.qmd
              - icon: translate
                text: Language Models
                href: blog/llm/llm.qmd
  twitter-card: true
  page-footer:
    background: light
    left: © Copyright 2024, Martin Laptev
    right:
      - icon: github
        href: https://github.com/maptv
        target: _blank
      - icon: linkedin
        href: https://linkedin.com/in/maptv
        target: _blank
      - icon: envelope-at
        href: mailto:maptv@engineer.com
format:
  html:
    page-layout: full
    mainfont: Lato
    toc: true
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    grid:
      sidebar-width: 161px
      body-width: 1800px
      margin-width: 240px
execute:
  freeze: true
  cache: true
