project:
  type: website
  output-dir: docs

website:
  title: "Martin Laptev"
  navbar:
    right:
      - icon: pencil
        href: https://maptv.github.io/blog
      - icon: github
        href: https://github.com/maptv
      - icon: linkedin
        href: https://linkedin.com/in/maptv
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

