author:
  - name: Martin Laptev
    url: https://maptv.github.io
project:
  type: website
  resources: .gitlab-ci.yml
  render:
    - "**/index.qmd"
  post-render:
  - asset/date.py
website:
  search:
    location: sidebar
    type: overlay
    keyboard-shortcut: ["/", "?", "h", "f", "s"]
    copy-button: true
    show-item-context: true
  page-navigation: true
  site-url: https://maptv.github.io
  repo-url: https://github.com/maptv/maptv.github.io
  repo-actions: [source]
  back-to-top-navigation: true
  reader-mode: true
  draft-mode: visible
  favicon: asset/deidek.svg
  navbar:
    title: Martin Laptev
    logo: asset/deidek.svg
    logo-alt: "Decagon made up of 100 triangles"
  sidebar:
    tools:
    - icon: github
      href: https://www.github.com/maptv
      target: _blank
    - icon: linkedin
      href: https://www.linkedin.com/in/maptv
      target: _blank
    - icon: envelope-at
      href: mailto:maptv@engineer.com
    collapse-level: 3
    contents:
    - icon: house-door
      text: Home
      href: index.qmd
    - icon: info-circle
      text: About
      href: about/index.qmd
    - icon: file-earmark-person
      text: CV/Résumé
      href: cv/index.qmd
    - icon: grid-3x3-gap
      text: Listing
      href: list/index.qmd
    - section: Art
      icon: brush
    - section: Cloud
      icon: cloud
    - section: History
      icon: hourglass-split
      contents:
        text: World War 2
        icon: 2-square
        href: history/ww2/index.qmd
    - section: Machine Learning
      icon: robot
      contents:
      - icon: dice-5
        text: Probablity
        href: ml/prob/index.qmd
      - icon: translate
        text: Language Models
        href: ml/llm/index.qmd
    - section: Measurement
      icon: rulers
      href: dec/index.qmd
      contents:
      - text: Ordinal date
        icon: calendar-event
        href: dec/date/index.qmd
      - text: Geoposition
        icon: geo
        href: dec/geo/index.qmd
      - text: Decimal time
        icon: clock
        href: dec/time/index.qmd
      - text: Daylight duration
        icon: sun
        href: dec/day/index.qmd
      - text: Time span
        icon: calendar-range
        href: dec/span/index.qmd
      - text: Navigation
        icon: compass
        href: dec/nav/index.qmd
      - text: Movement
        icon: arrows-move
        href: dec/move/index.qmd
      - text: Size
        icon: bounding-box-circles
        href: dec/size/index.qmd
    - section: Science
      icon: stars
    - section: Software
      icon: laptop
      contents:
      - icon: gear
        text: Setup
      - icon: git
        text: Git
        href: software/git/index.qmd
      - icon: p-square
        text: Positron
        href: software/positron/index.qmd
      - icon: journal-richtext
        text: Jupyter
        href: software/jupyter/index.qmd
      - icon: markdown
        text: Quarto Markdown
        href: software/quarto/index.qmd
      - icon: 0-circle
        text: Observable
        href: software/observable/index.qmd
  twitter-card: true
  page-footer:
    background: light
    left: © Copyright 2024, Martin Laptev
    right:
    - icon: github
      href: https://github.com/maptv
      target: _blank
    - icon: linkedin
      href: https://linkedin.com/in/maptv
      target: _blank
    - icon: envelope-at
      href: mailto:maptv@engineer.com
format:
  html:
    pagetitle: Martin Laptev
    page-layout: full
    mainfont: Lato
    toc: true
    theme:
      light: [flatly, asset/light.scss]
      dark: [darkly, asset/dark.scss]
    grid:
      sidebar-width: 162px
      body-width: 1800px
      margin-width: 162px
    css: asset/style.css
    anchor-sections: true
    tbl-cap-location: margin
    code-block-background: false
    code-block-border-left: false
    citations-hover: true
    footnote-hover: true
    code-copy: true
    code-fold: false
    code-link: true
    code-tools: true
    link-external-icon: false
    link-external-newwindow: true
    crossref:
      lst-title: List
      lst-prefix: List
    mermaid:
      theme: default
title-block-banner: false
execute:
  freeze: true
  cache: true
freeze: true
cache: true
lightbox: true
date-format: x
date: last-modified
toc: true
comments:
  giscus:
    repo: maptv/maptv.github.io
