project:
  type: website
  resources: .gitlab-ci.yml
website:
  page-navigation: true
  site-url: https://maptv.github.io
  repo-url: https://github.com/maptv/maptv.github.io
  repo-actions: [source]
  back-to-top-navigation: true
  reader-mode: true
  favicon: media/deidek.svg
  navbar:
    title: Martin Laptev
    logo: media/deidek.svg
    logo-alt: "Decagon made up of 100 triangles"
    right:
      - icon: house-door
        file: index.qmd
        text: Home
      - icon: info-circle
        file: about/index.qmd
        text: About
      - icon: pencil
        file: blog/index.qmd
        text: Blog
      - icon: file-earmark-person
        file: cv/index.qmd
        text: CV
      - icon: github
        href: https://github.com/maptv
        target: _blank
      - icon: linkedin
        href: https://linkedin.com/in/maptv
        target: _blank
      - icon: envelope
        href: mailto:maptv@engineer.com
  sidebar:
    collapse-level: 2
    contents:
      - text: About
        href: about
      - section: Blog
        href: blog
        contents:
          - section: Tools
            href: blog/#category=tool
            contents:
              - blog/git/git.qmd
              - blog/vscode/vscode.qmd
              - blog/quarto/quarto.qmd
              - blog/observable/observable.qmd
              - blog/jupyter/jupyter.qmd
              - blog/knitr/knitr.qmd
          - section: Machine Learning
            href: blog/#category=ml
            contents:
              - blog/prob/prob.qmd
              - blog/llm/llm.qmd
      - text: Curriculum Vitae
        href: cv
      - text: GitHub
        href: https://github.com/maptv
      - text: LinkedIn
        href: https://linkedin.com/in/maptv
      - text: Mail
        href: mailto:maptv@engineer.com
  twitter-card: true
  page-footer:
    background: light
    left: © Copyright 2024, Martin Laptev
    right:
      - icon: github
        href: https://www.github.com/maptv
      - icon: linkedin
        href: https://www.linkedin.com/in/maptv
format:
  html:
    page-layout: full
    mainfont: Lato
    toc: true
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    grid:
      sidebar-width: 150px
      body-width: 1800px
      margin-width: 250px
execute:
  freeze: true
  cache: true
