author:
  - name: Martin Laptev
    url: https://maptv.github.io
date-format: x
date: last-modified
project:
  type: website
  resources: .gitlab-ci.yml
  render:
    - "**/index.qmd"
  post-render:
  - asset/date.py
website:
  search:
    location: sidebar
    type: overlay
    keyboard-shortcut: []
    copy-button: true
    show-item-context: true
  page-navigation: true
  site-url: https://maptv.github.io
  repo-url: https://github.com/maptv/maptv.github.io
  repo-actions: [source]
  back-to-top-navigation: true
  reader-mode: true
  draft-mode: visible
  favicon: asset/deidec.svg
  navbar:
    title: Martin Laptev
    logo: asset/deidec.svg
    logo-alt: "Decagon made up of 100 triangles"
  sidebar:
    logo: ""
    tools:
    - icon: github
      href: https://www.github.com/maptv
      target: _blank
    - icon: linkedin
      href: https://www.linkedin.com/in/maptv
      target: _blank
    - icon: envelope-at
      href: mailto:maptv@engineer.com
    collapse-level: 2
    contents:
    - icon: house-door
      text: Home
      href: index.qmd
    - icon: info-circle
      text: About
      href: about/index.qmd
    - icon: file-earmark-person
      text: CV/Résumé
      href: cv/index.qmd
    - icon: grid-3x3-gap
      text: Article List
      href: list/index.qmd
    # - section: Art
    #   icon: brush
    # - section: Cloud
    #   icon: cloud
    - section: Dec
      icon: arrow-repeat
      href: dec/index.qmd
      contents:
      - text: Date
        icon: calendar-date
        href: dec/date/index.qmd
      - text: Time
        icon: clock
        href: dec/time/index.qmd
      - text: Snap
        icon: postage
        href: dec/snap/index.qmd
      - text: Span
        icon: calendar-range
        href: dec/span/index.qmd
    - section: History
      icon: hourglass-split
      contents:
        text: World War 2
        icon: 2-square
        href: history/ww2/index.qmd
    - section: Machine Learning
      icon: robot
      contents:
      - icon: dice-5
        text: Probablity
        href: ml/prob/index.qmd
      - icon: translate
        text: Language Models
        href: ml/llm/index.qmd
    # - section: Science
    #   icon: stars
    - section: Software
      icon: laptop
      contents:
      # - icon: gear
      #   text: Setup
      - icon: git
        text: Git
        href: git/index.qmd
      - icon: journal-richtext
        text: Jupyter
        href: jupyter/index.qmd
      - icon: 0-circle
        text: Observable
        href: observable/index.qmd
      - icon: p-square
        text: Positron
        href: positron/index.qmd
      - section: Quarto
        icon: markdown
        href: quarto/index.qmd
        contents:
        - text: Filter
          icon: funnel
          href: quarto/filter/index.qmd
        - text: Include
          icon: file-earmark-plus
          href: quarto/include/index.qmd
        - text: Script
          icon: file-code
          href: quarto/script/index.qmd
      - icon: file-slides
        text: Reveal
        href: reveal/index.qmd
  twitter-card: true
  page-footer:
    background: light
    left: © Copyright 2025, Martin Laptev
    right:
    - icon: github
      href: https://github.com/maptv
      target: _blank
    - icon: linkedin
      href: https://linkedin.com/in/maptv
      target: _blank
    - icon: envelope-at
      href: mailto:maptv@engineer.com
format:
  html:
    pagetitle: Martin Laptev
    page-layout: full
    mainfont: Tahoma, Palatino, Verdana, Times New Roman
    toc: true
    theme:
      light: [flatly, asset/light.scss]
      dark: [darkly, asset/dark.scss]
    grid:
      sidebar-width: 205px
      body-width: 900px
    css: asset/style.css
    anchor-sections: true
    tbl-cap-location: margin
    code-block-background: false
    code-block-border-left: false
    citations-hover: true
    footnote-hover: true
    code-copy: true
    code-fold: false
    code-link: true
    code-tools: true
    link-external-icon: false
    link-external-newwindow: true
    linestretch: 2
    crossref:
      lst-title: List
      lst-prefix: List
    mermaid:
      theme: default
  commonmark: default
citation:
  accessed: 2024
  issued: 2024
title-block-banner: false
execute:
  freeze: true
  cache: true
freeze: true
cache: true
lightbox: true
toc: true
# comments:
#   giscus:
#     repo: maptv/maptv.github.io
profile:
  default: knitr
