---
title: "Martin Skarzynski Laptev"
format:
  html:
    output-file: index.html
    toc: true
css: cv.css
format-links: [pdf]
---

#### [240-595-3460](tel:240-595-3460){.bi .bi-phone} []{.bi .bi-dot} [maptv@engineer.com](mailto:maptv@engineer.com){.bi .bi-envelope} []{.bi .bi-dot} [maptv.github.io](https://maptv.github.io){.bi .bi-house} []{.bi .bi-dot} [maptv](https://github.com/maptv){.bi .bi-github} []{.bi .bi-dot} [maptv](https://linkedin.com/in/maptv){.bi .bi-linkedin} {.centered}  

####### Cloud Computing []{.bi .bi-dot .blue} Data Science []{.bi .bi-dot} Machine Learning []{.bi .bi-dot} Technical Management []{.bi .bi-dot} Software Engineering []{.bi .bi-dot} Solution Architecture {.centered}  

### Mission

My goal is to lead the next generation of scientists and engineers in building solutions that integrate substantive expertise from diverse fields with machine intelligence.
Through my work, I strive to promote open source software, such as the Quarto publishing system, which I use to build dashboards, presentations, reports, websites, and other digital deliverables.
Overall, I aim to leverage my broad scientific background and technical expertise to help transform the promises of science and technology into a better future for all of humanity.

### Recent Experience

##### [Lead Instructor]{style="font-weight: 900;"}, [General Assembly](https://generalassemb.ly) [July 2019 ‑ Present]{.cvdate}

- Teaches [various courses](https://generalassemb.ly/instructors/martin-skarzynski/23420) such as:
  - [Data Analytics](https://generalassemb.ly/education/data-analytics)
  - [Front-End Web Development](https://generalassemb.ly/education/front-end-web-development)
  - [Tech Excellence Data Science](https://www.boozallen.com/e/insight/blog/path-to-technical-success)
  - [Python Programming](https://generalassemb.ly/education/python-programming)
  - [React Development](https://generalassemb.ly/education/react-development)

##### [Lead Instructor]{style="font-weight: 900;"}, [Data Society](https://datasociety.com) [October 2019 ‑ Present]{.cvdate}

- Teaches workshops such as:
  - Machine Learning
  - Data Science Bootcamp
  - Natural Language Processing
  - Deep Learning
  - Data Science Academy
  - Python Programming
  - DevOps
  - Data Visualization
  - R Programming

##### Vice President, [Data Community DC](https://www.datacommunitydc.org) [April 2022 ‑ Present]{.cvdate}

- Leads a non‑profit organization that supports [eleven Meetup groups](https://www.datacommunitydc.org/meetups-overview)

##### [Adjunct Professor]{style="font-weight: 900;"}, Virginia Tech [September 2021 ‑ December 2023]{.cvdate}

- Taught two graduate courses for the Computer Science and Statistics Departments:
  - [Machine Learning](https://cs.vt.edu/Graduate/Courses/GradCourseDescriptions.html#:~:text=CS%205805%2D6%20%2D%20Machine%20Learning%C2%A0)
  - [Data Analytics](https://cs.vt.edu/Graduate/Courses/GradCourseDescriptions.html#:~:text=CS%205525%2D6%20(STAT%205525%2D6)%20%2D%20Data%20Analytics)

##### [Senior Domain Lead]{style="font-weight: 900;"}, [Amazon Web Services](https://aws.amazon.com) [April 2022 ‑ February 2023]{.cvdate}

- Provided customers with scientific and technical expertise in:
  - [Computer Vision](https://aws.amazon.com/health/solutions/medicalimaging)
  - [Data Architecture](https://aws.amazon.com/big-data/datalakes-and-analytics/modern-data-architecture)
  - [Data Visualization](https://docs.aws.amazon.com/wellarchitected/latest/analytics-lens/data-visualization)
  - [Genomics](https://aws.amazon.com/health/genomics)
  - [Machine Learning](https://aws.amazon.com/health/machine-learning)
  - [Real World Evidence](https://aws.amazon.com/marketplace/solutions/healthcare/health-records)
- Built Artificial Intelligence (AI) solutions and Machine Learning Operations (MLOps) systems using:
  - [Amazon SageMaker](https://aws.amazon.com/sagemaker)
  - [AWS Developer Tools](https://aws.amazon.com/developer/tools##Browse_by_Tool_Type)
  - [AWS Lambda](https://aws.amazon.com/lambda)
  - [Amazon EventBridge](https://aws.amazon.com/eventbridge)
  - [AWS CloudFormation](https://aws.amazon.com/cloudformation)
  - [AWS IAM](https://aws.amazon.com/iam)
  - [Amazon EMR](https://aws.amazon.com/emr)
  - [AWS Databases](https://aws.amazon.com/products/databases)
  - [AWS Service Catalog](https://aws.amazon.com/servicecatalog)
- Obtained 3 AWS certification
  - [Solutions Architect Associate](https://www.credly.com/badges/1ae81600-c0cb-47b4-8610-e0c58bff6741/public_url)
  - [Cloud Practitioner](https://www.credly.com/badges/c3143f03-6ebb-4f16-827c-c89f8db2a3cf/public_url)
  - [Practical Data Science](https://www.coursera.org/account/accomplishments/specialization/certificate/MU388FKRUUL3)

##### AI Engineering Manager, [Booz Allen Hamilton](https://www.boozallen.com) [October 2019 ‑ March 2022]{.cvdate}

- Led a team of data scientists and software developers working on a cyber intelligence application
- Spearheaded interdisciplinary COVID‑19 [visualization](https://www.boozallen.com/c/insight/blog/epimaps-data-visualization-for-healthcare), [genomics](https://mskar.github.io/var), and statistical modeling efforts
- Obtained the [Microsoft Azure Data Scientist Associate](https://www.credly.com/badges/99aa294a-2b69-40f2-a607-0e7b91ffb5f6/public_url){.italic} certification
  
##### [Adjunct Professor]{style="font-weight: 900;"}, [George Washington University](https://www.gwu.edu) [September 2021 ‑ December 2023]{.cvdate}

- Taught two undergraduate courses for the [Women's Leadership Program](https://wlp.gwu.edu):
  - [Biology of Organisms](https://wlp.gwu.edu/science-health-and-medicine#:~:text=Introductory%20Biology%3A%20Biology%20of%20Organisms)
  - [Women and Leadership](https://wlp.gwu.edu/science-health-and-medicine#:~:text=Biology%20of%20Organisms-,Symposium,-The%20weekly%20symposia)

##### [Biomedical Scientist]{style="font-weight: 900;"}, [National Institutes of Health](https://www.nih.gov) [June 2009 ‑ April 2021]{.cvdate}

- Integrated clinical, laboratory, epidemiologic, genomic, and medical imaging data
- Combined deep learning and statistical inference using stacked ensembles
- Conducted genomic analysis of immune and cancer cells
- Developed and tested pharmaceutical and immunotherapeutic agents
- Quantified cancer cell signaling pathways
- Mentored trainees from four different NIH training programs:
  - [Summer Internship Program](https://www.training.nih.gov/research-training/pb/sip)
  - [Medical Research Scholars Program](https://clinicalcenter.nih.gov/training/mrsp)
  - [NIH HiSTEP](https://www.training.nih.gov/research-training/hs/hs-sip/histep)
  - Biomedical Research Training Program for Individuals from Underrepresented Groups

##### [Bioinformatics and Data Science Co-Chair]{style="font-weight: 900;"}, [FAES](https://faes.org) [January 2014 ‑ May 2020]{.cvdate}

- Co‑administered an academic program with over twenty faculty members
- Taught three graduate data science courses:
  - [Introduction to Python](https://github.com/biof309)
  - [Introduction to Text Mining](https://github.com/biof395)
  - [Applied Machine Learning](https://biof509.github.io)
- Taught nine graduate biotechnology workshops:
  - [Pharmacometric Analyses using R](https://education.faes.org/search/publicCourseSearchDetails.do?method=load&courseId=1059989)
  - [Cellular Immunology](https://education.faes.org/search/publicCourseSearchDetails.do?method=load&courseId=1409949)
  - [Research Tools for Studying Disease](https://education.faes.org/search/publicCourseSearchDetails.do?method=load&courseId=1151070)
  - Junior Scientist Training Program
  - Recombinant DNA Methodology
  - Genetics Institute
  - Immunochemistry and Antibodies
  - Cancer Prevention
  - Flow Cytometry

### Select Publications

##### [JAMA Netw Open]{style="font-weight: 900;"}, [[...] a deep learning model [...] to inform lung cancer screening intervals](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2802522) [March 2023]{.cvdate}

##### [Glob Health Epidemiol Genom]{style="font-weight: 900;"}, [SARS‐CoV‐2 genome‐based severity predictions correspond to [...] higher viral load](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9173902) [February 2023]{.cvdate}

##### [Virological]{style="font-weight: 900;"}, [Linking genotype to phenotype [...] in SARS‐CoV‐2 [...]](https://virological.org/t/linking-genotype-to-phenotype-further-exploration-of-mutations-in-sars-cov-2-associated-with-mild-or-severe-outcomes/794) [April 2022]{.cvdate}

##### [Evol Med Public Health]{style="font-weight: 900;"}, [Variants in SARS-CoV-2 associated with mild or severe outcome](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8385248) [June 2021]{.cvdate}

##### [J Natl Cancer Inst]{style="font-weight: 900;"}, [Using prediction models to reduce [...] disparities in [...] lung cancer screening [...]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8562965) [January 2021]{.cvdate}

##### [Clin Cancer Res]{style="font-weight: 900;"}, [Interactions between ibrutinib and anti‐CD20 antibodies [...]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4703510) [January 2016]{.cvdate}

##### [Bioconjug Chem]{style="font-weight: 900;"}, [Designing the furin‐cleavable linker in recombinant immunotoxins [...]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7724502) [May 2015]{.cvdate}

##### [Front Public Health]{style="font-weight: 900;"}, [Health disparities in the immunoprevention of [HPV] [...] associated malignancies](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4682020) [December 2015]{.cvdate}

##### [Blood]{style="font-weight: 900;"}, [Pathogenic role of [BCR] signaling and canonical NF-κB activation in [MCL]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4937360) [July 2016]{.cvdate}

##### [Cancer Res]{style="font-weight: 900;"}, [Harnessing the Fcμ receptor for [...] therapy of [CLL]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4268434) [October 2014]{.cvdate}

### Education

##### [MPH]{style="font-weight: 900;"}, Epidemiology and Biostatistics [May 2018]{.cvdate}

##### [PhD]{style="font-weight: 900;"}, Tumor Biology [May 2015]{.cvdate}

##### [MS]{style="font-weight: 900;"}, Biotechnology [June 2009]{.cvdate}

##### [BA]{style="font-weight: 900;"}, Biology [May 2007]{.cvdate}

### Select Awards

##### [Community Contribution of the Year Category Finalist]{style="font-weight: 900;"}, AWS Builder Awards [February 2023]{.cvdate}

##### [Artificial Intelligence Solutions Architect Award]{style="font-weight: 900;"}, BAH Emergent Skills Program [January 2022]{.cvdate}

##### [Trans‐Fellowship Research Award]{style="font-weight: 900;"}, Cancer Prevention Fellowship Program [June 2019]{.cvdate}

##### [Fellows Award for Research Excellence]{style="font-weight: 900;"}, National Institutes of Health [June 2015]{.cvdate}

##### [Orloff Science Award]{style="font-weight: 900;"}, National Heart, Lung, Blood Institute [October 2014]{.cvdate}

##### [Director's Science Award]{style="font-weight: 900;"}, National Heart, Lung, Blood Institute [January 2014]{.cvdate}

```{=html}
<script src="../scripts/time.js"></script>
<script>
const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>
<style>
div#quarto-sidebar-glass { display: none !important; }
ul.navbar-nav.navbar-nav-scroll { -webkit-flex-direction: row !important; }
#quarto-sidebar { padding: 0px; overflow-x: hidden !important; }
#quarto-sidebar > * { padding: 0px; }
@media only screen and (max-width: 991px) { #quarto-search { display: none !important; } #quarto-sidebar { padding: 0px 9px 0px 9px !important; } }
@media only screen and (max-width: 767px) { div.cell.page-columns.page-full { display: none !important; } }
</style>
```