# Glossary {.unnumbered #glos}

::: {.column-page-right #gloslist}
- [a](#arcbeat){#ab}: arcbeat, a hundred thousandth of a circle, 0.0036 degrees, 0.216 arcminutes, 12.96 arcseconds
- [b](#beat){#b}: beat, centimilliday, a hundred thousandth of a day, 864 milliseconds
    - [mb](#millibeat){#mb}: millibeat, centimicroday, a thousandth of a beat, a hundred millionth of a day, 864 microseconds
- [bpc](#beatpercentiday){#bpc}: a musical or heart beat per centiday, a tenth of a beat per milliday, 0.069[4]{.vinculum} beats per minute, 100 beats per day
- [bpm](#beatpermilliday){#bpm}: a musical or heart beat per milliday, ten beats per centiday, 0.69[4]{.vinculum} beats per minute, 1000 beats per day
- [bmi](#bodymassindex){#bmi}: body mass index, kilograins of body mass divided by height in zem squared (kg/z&sup2;)
- [c](#taur){#c}: taur, 𝜏*r*, 100000 kilozem, 40000 kilometers, nearly the circumference of the Earth, roughly the product of 𝜏 and the radius of the Earth, approximately the dividend of the surface area and the diameter of the Earth
    - [gc](#gigataur){#gc}: gigataur, a billion taur
    - [kc](#kilotaur){#kc}: kilotaur, a thousand taur, 10^8^ kilozem
    - [mc](#millitaur){#mc}: millitaur, *m*𝜏*r*, a thousandth of a taur, 100 kilozem, 40 kilometers
    - [nc](#nanotaur){#nc}: nanotaur, *n*𝜏*r*, a billionth of a taur, 100 millizem, 1 decizem, 4 centimeters
    - [nc&sup3;](#cubicnanotaur){#nc3}: cubic nanotaur, *n*𝜏*r*&sup3;, 1 cubic decizem
- [d](#day){#d}: day, a tenth of a decaday, a seventh of a week, a fifth of a pentaday, 10 decidays, 24 hours, 100 centidays, 1000 millidays, 1440 minutes, 86400 seconds, 100000 beats, the inverse of a quotidie
    - [dox](#dayofxun){#dox}: day of xún
    - [dop](#dayofpentaday){#dop}: day of pentaday
    - [dom](#dayofmonth){#dom}: day of month
    - dom~♀~: Decyther day of month, 0 to 28 in Venusian short months or 0 to 29 in Venusian long months
    - [dow](#dayofweek){#dow}: day of week
    - [doy](#dayofyear){#doy}: day of year, xún * 10 + dox
    - [pid](#positiveintegerdoy){#pid}: positive integer day of year, days elapsed since the beginning of the year, 0 to 364 or 365
    - [nid](#negativeintegerdoy){#nid}: negative integer day of year, pid - syl, -365 or -366 to -1, the negative of the days left in the year
    - [mid](#mixedintegerdoy){#mid}: mixed integer day of year, an nid rewritten with negative leading digits (marked by a vinculum) and a positive last digit or two
    - [doe](#dayofera){#doe}: day of era, days since the Dec epoch
    - [eda](#epochaldayaggregate){#eda}: epochal day aggregate, doe + tod, days since the Dec epoch including the time of day
    - [edd](#edadifferencedifference){#edd}: eda difference difference, an eda minus a difference, used to recover the year and ada of a past event
    - [ada](#annualdayaggregate){#ada}: annual day aggregate, doy + tod
    - [doc](#dayofcycle){#doc}: day of cycle, days since the start of the current 400-year Gregorian cycle, 0 to 146096
    - doc~♀~: Decyther day of cycle, days since the start of the current 467-day Venusian cycle, doe mod 467, 0 to 466
    - [doh](#dayofhectoday){#doh}: day of hectoday, doy mod 100, the percent of a hectoday that has elapsed
    - [dob](#dayofbimester){#dob}: day of bimester, 0 to 58 in common bimesters or 0 to 59 in leap bimesters
    - dob~♀~: Decyther day of bimester, 0 to 57 in antes and the post of Qoc 2 or 0 to 58 in the other posts
    - [dot](#dayoftricennium){#dot}: day of tricennium, days since the start of the current 30-year lunar cycle, 0 to 10630
    - [doq](#dayofquadrimester){#doq}: day of quadrimester, days since the beginning of a Decyther quadrimester, 0 to 115 or 116
    - [boq](#beginningofquadrimester){#boq}: beginning of quadrimester, the pid of Doq 0, pid - doq
    - [qoc](#quadrimesterofcycle){#qoc}: quadrimester of cycle, zero-based index of a Decyther quadrimester, 0 to 3
    - [bob](#beginningofbimester){#bob}: beginning of bimester, the pid of Dob 0, pid - dob
    - [bom](#beginningofmonth){#bom}: beginning of month, the pid of the day before the first day of the month, pid - dom
    - [moc](#monthofcycle){#moc}: month of cycle, zero-based index of a Venusian month, 0 to 15
    - [bow](#beginningofweek){#bow}: beginning of week, the pid of Dow 0, pid - dow
    - [boy](#beginningofyear){#boy}: beginning of year, midnight at the start of Day 0
    - [boe](#beginningofera){#boe}: beginning of era, midnight at the start of Day 0 of Year 0
    - [boc](#beginningofcycle){#boc}: beginning of cycle, the start of Doc~♀~ 0 and of the first ante in a Decyther cycle
    - [eoy](#endofyear){#eoy}: end of year, midnight at the end of Day 364 or 365
    - [jdn](#Juliandaynumber){#jdn}: Julian day number, days since the start of the Julian period; increments at noon UTC
    - [lid](#lunarintercalationdifference){#lid}: lunar intercalation difference, a lunar nid that only resets after lunar leap years, -1063 to -1
    - [ved](#venusianextracalationdifference){#ved}: Venusian extracalation difference, days until the end of Doc~♀~ 349, the last day of the one-day-shorter Qoc 2, Bimester 5, and Moc 11, (doc~♀~ + 117) mod 467 - 467, -467 to -1
    - [mud](#misalignedunitdifference){#mud}: misaligned unit difference, pid - dom - dow
    - [dd](#deciday){#dd}: deciday, a tenth of a day, 2.4 hours, 144 minutes
    - [cd](#centiday){#cd}: centiday, a hundredth of a day, 0.24 hours, 14.4 minutes
    - [md](#milliday){#md}: milliday, a thousandth of a day, 1.44 minutes
    - [cmd](#centimilliday){#cmd}: centimilliday, a hundred thousandth of a day, 1 beat, 864 milliseconds
    - [µd](#microday){#ud}: microday, a millionth of a day, 86.4 milliseconds
    - [nd](#nanoday){#nd}: nanoday, a billionth of a day, 86.4 microseconds
- [°](#degree){#deg}: degree, 1/360 turns, 180/𝜋 or 360/𝜏 radians
    - [c°](#compassdegree){#cdeg}: compass degree
    - [h°](#huedegree){#hdeg}: hue degree
- [e](#egg){#e}: egg, 1000 grains, 2 ounces, 64 grams
- [eot](#equationoftime){#eot}: equation of time, ast - mst as a function of toy, about -9.8 to 11.4 millidays
- [ℓ](#cubit){#ell}: ell, cubit, 10/9 zem
- [f](#foot){#f}: foot, 0.75 zem, 75 millimeters 
- [g](#gutta){#g}: drop (gutta in Latin) or grain (granum in Latin), 64 microliters or 64 milligrams
    - [kg](#kilograin){#kg}: kilograin or kilodrop, 64 grams or 64 milliliters
    - [Mg](#megagrain){#Mg}: megagrain or megadrop, 64 kilograms or 64 liters
- [h](#hectoday){#h}: a Dec season, 1 ***h***ectoday, 10 decadays, or one ***h***undred days
    - [pih](#positiveintegerhectoday){#pih}: positive integer hectoday, &LeftFloor;pid &div; 100&RightFloor;, 0 to 3
    - [nih](#negativeintegerhectoday){#nih}: negative integer hectoday, &LeftFloor;nid &div; 100&RightFloor;, -4 to -1
- [hex](#hexadecimal){#hex}: hexadecimal, base 16
- [hsl](#huesaturationlightness){#hsl}: hue saturation lightness
- [hsv](#huesaturationvalue){#hsv}: hue saturation value
- [i](#inch){#i}: inch, a sixteenth of a zem, 25 millimeters
- [iso](#internationalorganizationforstandardization){#iso}: [International Organization for Standardization](https://en.wikipedia.org/wiki/International_Organization_for_Standardization), the body behind ISO 8601 dates such as 1970-01-01 (ISO month date) and 1970-W01-4 (ISO week date)
- [k](#keg){#k}: keg, cubic zem, 64 liters, 1000 wine glasses, a million drops, half a barrel
- [km](#kilometer){#km}: kilometer, 1000 meters, 2500 zem, 2.5 kilozem
- [kmph](#kilometersperhour){#kmph}: kilometers per hour, thousands of meters per hour, 1 kmph = 0.6 mv
- [L](#liter){#L}: liter, 15625 drops, a cubic decimeter
    - [mL](#milliliter){#mL}: milliliter, a cubic centimeter, a thousandth of a liter, 15.625 drops
    - [µL](#microliter){#uL}: microliter, a cubic millimeter, a millionth of a liter, 0.015625 drops
- [m](#meridian){#m}: meridian, a full circle around the Earth moving North or South; used in the abbreviations a.m. (antemeridian) and p.m. (postmeridian); the letter "m" in meridian can be vertically flipped to get the letter "w" in wěi
    - [dm](#decimeridian){#dm}: decimeridian, a tenth of a meridian
    - [mm](#millimeridian){#mm}: millimeridian, a thousandth of a meridian
- [m&sup2;](#squaremeter){#m2}: square meter, 6.25 square zem
    - [cm&sup2;](#squarecentimeter){#cm2}: square centimeter, 6.25 square centizem
    - [dm&sup2;](#squaredecimeter){#dm2}: square decimeter, 6.25 square decizem
    - [km&sup2;](#squarekilometer){#km2}: square kilometer, 6.25 square kilozem
    - [cm&sup3;](#cubiccentimeter){#cm3}: cubic centimeter, 1 milliliter, a thousandth of a liter, 15.625 drops
- [p](#pentaday){#p}: pentaday, a group of five days, half a decaday
    - [pox](#pentadayofxun){#pox}: pentaday of xún, 0 for Dox 0 to 4 and 1 for Dox 5 to 9
    - [pob](#pentadayofbimester){#pob}: pentaday of bimester, &LeftFloor;dob &div; 5&RightFloor;, 0 to 11
    - [pir](#pentadayinterquintilerange){#pir}: pentaday interquintile range, Dop 1 to 3, the three days between two lim
    - [lim](#liminalinterconnectingmargin){#lim}: liminal interconnecting margin, the pair of days between two pir, Dop 4 and the following Dop 0
- [n](#note){#n}: note, a specific frequency within an octave
- [NOAA](#nationaloceanicandatmosphericadministration){#noaa}: [National Oceanic and Atmospheric Administration](https://www.noaa.gov), source of the General Solar Position Calculations document
- [o](#octave){#o}: octave, a two fold change in frequency
  - [do](#decioctave){#do}: decioctave, a tenth of a two fold change in frequency
- [þ](#perbeat){#per}: perbeat, the inverse of a beat, 1/beat, once per beat, every beat, 100000 q; symbolized by thorn (þ), which looks like a combination of the letters "p" and "b"; not to be confused with a picobeat (pb)
    - [Tþ](#teraperbeat){#Tpb}: teraperbeat, 10^12^ perbeat, the inverse of a picobeat, 1/picobeat, once per picobeat, every picobeat
- [q](#quotidie){#q}: quotidie, the inverse of a day, a hundred thousandth of a perbeat; the letter "q" in quotidie can be flipped vertically to produce the letter "d" in day
- [r](#rose){#r}: compass rose, a full circle along the horizon, 360 compass degrees
    - [saa](#solarazimuthangle){#saa}: solar azimuth angle, the direction of the Sun along the horizon measured clockwise from North
    - [mr](#millirose){#mr}: compass millirose, a thousandth of a circle along the horizon, .36 compass degrees
- [rad](#radian){#rad}: radian, $1\over\tau$ turns, $360\over\tau$ degrees, $1\over 2\pi$ turns, $180\over\pi$ degrees
- [rgb](#redgreenblue){#rgb}: red green blue
- [s](#second){#s}: second, 1/90 millidays, 0.9 beats, 1 Dec second = 0.96 SI seconds
- [soi](#spinorbitinterval){#soi}: spin orbit interval, a lunar day, 1.03505 days
    - [soy](#soiofyear){#soy}: soi of year
    - [sob](#soiofbimester){#sob}: soi of bimester
- [SI](#internationalsystemofunits){#si}: [International System of Units](https://en.wikipedia.org/wiki/International_System_of_Units#:~:text=the%20world%27s%20most%20widely%20used%20system%20of%20measurement)
- [sol](#speedoflight){#sol}: speed of light, 647.55170928 kiloomegar, 299792458 meters per second
- [sos](#speedofsound){#sos}: speed of sound, 735.048 milliomegar, 340.3 meters per second
- [sda](#solardeclinationangle){#sda}: solar declination angle, the latitude at which the Sun is directly overhead
- [𝜏](#tau){#2pi}: 2𝜋 or approximately 6.2831853
    - [𝜋](#taudividedby2){#pi}: pi, 𝜏/2 or approximately 3.1415927
    - [ϡ](#taudividedby900){#sampi}: sampi, the Greek numeral for 900, 𝜏/900 or approximately 0.0069813 radians, 0.4 degrees
- [Tenet](#tenequaltemperament){#tenet}: ten equal temperament
    - [Xet](#10et){#xet}: Tenet
    - [12et](#twelveequaltemperament){#12et}: twelve equal temperament
- [tod](#timeofday){#tod}: time of day
    - [hms](#hourminutesecond){#hms}: hour minute second, a tod written as an hod, moh, and som triplet
    - [dsa](#dailysecondaggregate){#dsa}: daily second aggregate, seconds since midnight, tod &times; 86400
    - [hsa](#hourlysecondaggregate){#hsa}: hourly second aggregate, seconds since the top of the hour, dsa mod 3600
    - [hod](#hourofday){#hod}: hour of day, &LeftFloor;dsa &div; 3600&RightFloor;, 0 to 23
    - [moh](#minuteofhour){#moh}: minute of hour, &LeftFloor;hsa &div; 60&RightFloor;, 0 to 59
    - [som](#secondofminute){#som}: second of minute, &LeftFloor;hsa mod 60&RightFloor;, 0 to 59
    - [mst](#meansolartime){#mst}: mean solar time, solar time based only on longitude and the Zone 0 tod
    - [ast](#apparentsolartime){#ast}: apparent solar time, mst + eot(toy), solar time based on the actual position of the Sun
    - [da](#dayarc){#da}: day arc, the time from sunrise to sunset, sunset - sunrise
    - [da/2](#halfdayarc){#da2}: half day arc, the time from sunrise to solar noon or from solar noon to sunset
    - [na](#nightarc){#na}: night arc, the time from sunset to sunrise, 1 - da
    - [na/2](#halfnightarc){#na2}: half night arc, the time from sunset to solar midnight or from solar midnight to sunrise
- [t](#turn){#t}: turn, 360 degrees, 𝜏 or 2𝜋 radians
    - [ct](#centiturn){#ct}: centiturn, a hundredth of a turn, 3.6 degrees, 𝜏/100 or 𝜋/50 radians
    - [dt](#deciturn){#dt}: deciturn, a tenth of a turn, 36 degrees, 𝜏/10 or 𝜋/5 radians
    - [mt](#milliturn){#mt}: milliturn, a thousandth of a turn, .36 degrees, 𝜏/1000 or 𝜋/500 radians
- [tzo](#timezoneoffset){#tzo}: time zone offset
- [u](#ounce){#u}: ounce (uncia in Latin), 500 grains, 32 grams, 500 drops, 32 milliliters
- [uto](#universaltimeoffset){#uto}: universal time offset, the offset in decidays that turns a Zone 0 tod into Universal Time; a tzo is an integer uto
    - [sto](#solartimeoffset){#sto}: solar time offset, a uto that is a terminating decimal
    - [eof](#exactoffsetfraction){#eof}: exact offset fraction, an irreducible fraction that expresses a repeating decimal uto exactly
    - [rod](#roundedoffsetdecimal){#rod}: rounded offset decimal, a repeating decimal uto rounded to a few digits
    - [ref](#roundofferrorfraction){#ref}: roundoff error fraction, uto - rod
- [utc](#coordinateduniversaltime){#utc}: [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time#:~:text=the%20primary%20time%20standard%20globally%20used%20to%20regulate%20clocks%20and%20time)
- [US](#unitedstates){#us}: [United States](https://en.wikipedia.org/wiki/Imperial_and_US_customary_measurement_systems)
- [UT](#universaltime){#ut}: [Universal Time](https://en.wikipedia.org/wiki/Universal_Time#:~:text=a%20time%20standard%20based%20on%20Earth%27s%20rotation), a time standard based on the rotation of the Earth
- [v](#omegar){#v}: omegar, ωr, 1041.[6]{.vinculum} miles per hour, 1.[6]{.vinculum} megameters per hour, 0.4[629]{.vinculum} kilometers per second, roughly 1.36 times the speed of sound
    - [kv](#kiloomegar){#kv}: kiloomegar, kωr, 1.[6]{.vinculum} gigameters per hour, 0.4[629]{.vinculum} megameters per second, approximately 0.1544% of the speed of light
    - [mv](#milliomegar){#mv}: milliomegar, mωr, 1.041[6]{.vinculum} miles per hour, 1.[6]{.vinculum} kilometers per hour, 0.4[629]{.vinculum} meters per second, approximately 0.136% of the speed of sound
- [w](#wei){#w}: wěi (纬), parallel, a measure of longitude; can be thought of as a measure of the **w**idth of a meridian on **E**arth; the letter "w" in wěi can be vertically flipped to get the letter "m" in meridian
    - [dw](#deciwei){#dw}: deciwěi, a tenth of a wěi (纬), a tenth of a parallel
    - [mw](#milliwei){#mw}: milliwěi, a thousandth of a wěi (纬), a thousandth of a parallel
- [x](#xun){#x}: xún (旬), decaday, a group of ten days, 2 pentadays, represented by x like the Roman numeral X
    - [pix](#positiveintegerxun){#pix}: positive integer xún, &LeftFloor;pid &div; 10&RightFloor;, 0 to 36
    - [nix](#negativeintegerxun){#nix}: negative integer xún, &LeftFloor;nid &div; 10&RightFloor;, -37 to -1
    - [mix](#mixedintegerxun){#mix}: mixed integer xún, the first two digits of an nih mid
    - [xir](#xuninterdecilerange){#xir}: xún interdecile range, Dox 1 to 8, the days between Dox 0 and 9
- [y](#year){#y}: year
    - [my](#milliyear){#my}: milliyear, a thousandth of a year
    - [yoe](#yearofera){#yoe}: year of era, integer years since the Dec epoch
    - [eya](#epochalyearaggregate){#eya}: epochal year aggregate, yoe + toy, years since the Dec epoch including the fraction of the current year
    - [toy](#timeofyear){#toy}: time of year, the fraction of the year that has elapsed, eya mod 1, ada &div; syl
    - [ymd](#yearmonthday){#ymd}: year month day, a Gregorian calendar date triplet
    - [syl](#solaryearlength){#syl}: solar year length, 365 or 366 days, pid - nid
    - [lyl](#lunaryearlength){#lyl}: lunar year length, 354 or 355 days
    - [cey](#commonerayear){#cey}: common era year, an ISO 8601 (Gregorian calendar) year number
    - [coe](#cycleofera){#coe}: cycle of era, 400-year cycles since the Dec epoch
    - [yoc](#yearofcycle){#yoc}: year of cycle, years since the start of the current 400-year cycle, 0 to 399
    - [yot](#yearoftricennium){#yot}: year of tricennium, lunar years since the start of the current 30-year lunar cycle, 0 to 29
    - [moy](#monthofyear){#moy}: month of year, zero-based, Moy 0 is March
    - [woy](#weekofyear){#woy}: week of year, (boydow + bow) &div; 7, 0 to 53
    - [wom](#weekofmonth){#wom}: week of month
- [z](#zoneequatorialmeter){#z}: zem, zone equatorial meter, 4 decimeters, 16 inches
    - [kz&sup2;](#squarekilozem){#kz2}: square kilozem, a million square zem, megahexamilliare, Mx, hexakilare, 16 hectares, 1600 ares, 40 acres, 0.16 square kilometers, 0.0625 square miles
    - [kz](#kilozem){#kz}: kilozem, 1000 zem, 400 meters, a quarter mile
    - [z&sup2;](#squarezem){#z2}: square zem, hexamilliare, 16 square decimeters, 1.[7]{.vinculum} square feet, 256 square inches
    - [cz&sup2;](#squarecentizem){#cz2}: square centizem, a ten-thousandth of a square zem, 16 square millimeters
    - [Dz&sup2;](#squaredecazem){#Dz2}: square decazem, 1 hexadeciare, 16 square meters, 19.75 square yards, 100 square zem
    - [z&sup3;](#cubiczem){#z3}: cubic zem, 1 keg, 64 liters, 1000 wine glasses, a million drops, half a barrel
    - [dz&sup3;](#cubicdecizem){#dz3}: cubic decizem, 1000 drops, 64 milliliters, 2 ounces, 1 wine glass
    - [cz&sup3;](#cubiccentizem){#cz3}: cubic centizem, 1 drop, 64 microliters
    - [dz](#decizem){#dz}: decizem, a tenth of a zem, 4 centimeters
    - [cz](#centizem){#cz}: centizem, a hundredth of a zem, 4 millimeters
    - [mz](#millizem){#mz}: millizem, a thousandth of a zem, 0.4 millimeters
:::
