on:
  workflow_dispatch:
  push:
    branches: [gh-pages]

name: Update Quarto Pub

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Publish to Quarto Pub
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
          render: false
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
